version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lps_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - lps_net

    web:
        image: nginx:alpine
        container_name: lps_web
        ports:
            - "8093:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - lps_net

    db:
        image: postgres:15
        container_name: lps_db
        environment:
            POSTGRES_DB: lps_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
        ports:
            - "5440:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - lps_net
    
    ai_service:
        build:
            context: ./python_service
            dockerfile: Dockerfile
        container_name: lps_ai
        ports:
            - "5000:5000"
        volumes:
            - ./public/assets/baju:/shared/assets/baju
        networks:
            - lps_net
        restart: unless-stopped

    ar_service:
        build:
            context: ./python_service_ar
            dockerfile: Dockerfile
        container_name: lps_ar
        ports:
            - "5001:5000"
        volumes:
            - ./public/assets/gallery:/shared/assets/gallery
        networks:
            - lps_net
        restart: unless-stopped


networks:
    lps_net:

volumes:
    db_data:
